name: mastodon tweet

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '*/15 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: |
        job_time=15
        export GOPATH=$HOME/go
        export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
        curl -sL https://github.com/syui/twg/releases/download/0.3.1/linux_amd64_twg -o twg
        chmod +x twg
        mkdir -p ~/.config/twg
        cat .config/twg/user.json| jq ".|=. + {\"Token\":\"${{ secrets.TWITTER_TOKEN }}\",\"Secret\":\"${{ secrets.TWITTER_SECRET }}\"}" > t
        mv t ~/.config/twg/user.json
        url=https://mstdn.syui.cf/api/v1
        j=mastodon.json
        user_id=1
        url="$url/accounts/$user_id/statuses?limit=40"
        curl -sSL "$url" -H "Authorization: Bearer ${{ secrets.MASTODON_ACCESS_TOKEN }}" > $j
        post=`cat $j|jq -r ".[]|select(.tags != [])|select(.tags|.[].name == \"twitter\")|.content"|sed -e 's/<[^>]*>//g' -e 's/#twitter//g'`
        if [ -z "$post" ];then
                echo no tag post
                exit
        fi
        date=`cat $j|jq -r ".[]|select(.tags != [])|select(.tags|.[].name == \"twitter\")|.created_at"`
        now=`date +%s -d "$job_time minutes ago"`
        for (( i=1;i<=`echo "$date"|wc -l`;i++ ))
        do
                date_t=`echo "$date"|awk "NR==${i}"`
                date_t=`date --date="$date_t" +%s`
                post_t=`echo "$post"|awk "NR==${i}"`
                if [ "$date_t" -gt "$now" ];then
                        echo $post_t
                        ./twg p "$post_t"
                fi
        done
